### ISSUE TITLE
Old-style /event links 404s

### ISSUE THREAD

**Issue by barrymcgee** [canonical-websites/blog.ubuntu.com#360] opened 2018-05-15 11:49 UTC
## Summary

Many links now 404 resulting in broken tests in the jujucharms.com codebase.

e.g

https://insights.ubuntu.com/event/ibm-edge-2015/

## Expected result

This link should redirect and resolve as a 200 with correct information.

**Comment by nottrobin** [comment] 2018-05-15 14:17
Duplicate of https://github.com/canonical-websites/blog.ubuntu.com/issues/234

**Closed by nottrobin** 2018-05-15 14:17 UTC
Labels: Type: Bug
