### ISSUE TITLE
Implement "preview post" functionality

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/blog.ubuntu.com#272] opened 2018-03-20 16:53 UTC

**Comment by steverydz** [comment] 2018-04-16 19:16
Need backend work to get around auth so we can expose unpublished posts

**Comment by anasereijo** [comment] 2019-03-13 11:49
@nottrobin is this something we can do in a future iteration?

**Comment by nottrobin** [comment] 2019-03-14 17:22
Duplicate of https://github.com/canonical-websites/blog.ubuntu.com/issues/273

Or rather, I don't think that one needs to be an epic when it only contains one issue, it's unnecessary duplication. So I've converted #273 to an issue, and I'll close this.

**Closed by nottrobin** 2019-03-14 17:22 UTC
Labels: Priority: Medium, Status: Blocked, Type: Enhancement
